name: Build and Deploy
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    name: Build LaTeX
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Identify LaTeX files
        run: |
          {
            echo 'GITHUB_FILE_PATHS<<EOF'
            echo "$(printf '%s\n' *.tex)"
            echo EOF
          } >> $GITHUB_ENV
      - name: Compile LaTeX files
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{env.GITHUB_FILE_PATHS}}
      - name: Upload PDF files
        uses: actions/upload-artifact@v3
        with:
          name: resumes
          path: '*.pdf'
    
  deploy:
    name: Deploy Resumes
    needs: build_latex
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download PDF files
        uses: actions/download-artifact@v4.1.7
        with:
          name: resumes
          path: public
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

