name: Build Resumes
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    name: Build LaTeX
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Identify LaTeX files
        run: |
          {
            echo 'GITHUB_FILE_PATHS<<EOF'
            echo "$(printf '%s\n' *.tex)"
            echo EOF
          } >> $GITHUB_ENV
      - name: Compile LaTeX files
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{env.GITHUB_FILE_PATHS}}
      - name: Upload PDF files
        uses: actions/upload-artifact@v3
        with:
          name: resumes
          path: '*.pdf'